name: CI/CD Pipeline
on: [push]  # Triggers on code push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out code
      - name: Install dependencies
        run: npm install  # Or `pip install -r requirements.txt` for Python
      - name: Run tests
        run: npm test    # Or `pytest` for Python

  deploy:
    needs: test          # Runs only if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging
        run: echo "Deploying to staging server..."  # Replace with actual deploy command
